Poc/flex gap
modulz/design-system pull request #21
Opened 2020-12-20 14:29 UTC by hadihallak

I _think_ this is working well now
spent a lot of time experimenting with different values and I'm hoping that this is the magical CSS combination

the component assumes that gap is supported on the server but once it hits the client it will do check gap support and if needed it will re-render and polyfill gap support. this way the majority of the time the component will not be polyfilling.

the main design system page on this PR is now using this gap polyfilled flex component so you can test and compare on different browsers.

2020-12-20 21:18 UTC, StephenHaney reviewed
I think the solution you came up with regarding SSR and only impacting Safari is great. I'll leave other feedback to the maintainers of the DS, but consider this good to go (after it's cleaned up) from my perspective.

As noted in Slack, we'll need to `import { Flex as Box }` in our Composer code export after switching to using the Flex component.

2020-12-21 07:15 UTC, hadihallak commented on components/Flex.tsx
> +const resolveUtils = (css, resolved = {}): any => {
This is needed because the flex properties might be hidden under utils so the component is resolving utils beforehand so that it's only dealing with standard CSS ones.

I'm thinking the new stitches could provide this css resolving function when we do `createCss`

2020-12-21 07:16 UTC, hadihallak commented on stitches.config.ts
> +  p: (value) => ({
nothing changed here other than moving utils to a module scoped exported const

2020-12-21 07:16 UTC, hadihallak commented on stitches.config.ts
> +  p: (value) => ({
same for breakpoints

2020-12-21 07:49 UTC, colmtuite approved these changes

2020-12-21 10:25 UTC, vladmoroz requested changes
Overall, this works great.

There's only two things I noticed that are breaking:
- `style` property doesn't work on Flex

  ```
  <Box css={{ backgroundColor: 'pink', width: '500px', margin: 'auto' }}>
    <Flex style={{ gap: '20px', backgroundColor: 'lime' }}>
      Text node
      <Box>Box</Box>
    </Flex>
  </Box>
  ```
  
  Chrome and Safari:
  <img width="790" alt="Screenshot 2020-12-21 at 12 20 54" src="https://user-images.githubusercontent.com/8441036/102766631-1d878a00-4387-11eb-8d41-c74ce96e892d.png">


- The layout breaks when Flex has text nodes as direct children (might be OK for now)

  ```
  <Box css={{ backgroundColor: 'pink', width: '500px', margin: 'auto' }}>
    <Flex css={{ gap: '20px', backgroundColor: 'lime' }}>
      Text node
      <Box>Box</Box>
    </Flex>
  </Box>
  ```
  
  Chrome:
  
  <img width="790" alt="Screenshot 2020-12-21 at 12 20 37" src="https://user-images.githubusercontent.com/8441036/102766805-5f183500-4387-11eb-8549-cdcb1c9c5348.png">
  
  Safari:
  
  <img width="790" alt="Screenshot 2020-12-21 at 12 20 43" src="https://user-images.githubusercontent.com/8441036/102766832-66d7d980-4387-11eb-845d-fa7a2c95f762.png">

2020-12-21 22:39 UTC, hadihallak commented
@vladmoroz 
Thanks for this through testing 👏 

> style property doesn't work on Flex. I guess this means it will break how Composer's exported code looks as it just uses style.

this is now fixed

> The layout breaks when Flex has text nodes as direct children 

>(might be OK for now)

yeah, i agree because solving this will not be possible in CSS land only as we can't target text nodes with CSS so we will likely need to iterate over the children and replace any text node with a span that we can target. but yeah should be fine for now and we can make this more js heavy to perfect it later if needed

2020-12-21 23:03 UTC, vladmoroz approved these changes
LGTM 🔥

2020-12-21 23:10 UTC, merged